#!/usr/bin/env python3
"""Build-time SFX converter for the iPod Nano 2G / Rockbox port.

Concatenates ccleste's original sound-effect clips (vendored under
ports/SDL2/Sources/CelesteSDL2/Resources/data/, already used by that port)
into one PCM16 mono blob, plus a C offset/length table mixer.c indexes by
sound id (see plugin/mixer.c's rb_audio_sfx). All snd*.wav are already
16-bit PCM mono at a uniform 22050Hz, so unlike ports/3DS's gen_audio.py this
needs no resampling/decoding step (and no macOS-only `afconvert` dependency)
-- it's pure Python, wav in, blob out.

Music (musN.ogg) isn't handled yet -- see ports/iPod/README.md's phased
audio plan; mixer.c's rb_audio_music is still a no-op.

Emits:
  <out>/sfx.bin          -- every sndN.wav's PCM16 samples, concatenated in
                            id order. NOT linked into celeste.rock -- it's
                            installed to /.rockbox/celeste/sfx.bin on the
                            device/simulator and loaded at runtime (see
                            plugin/mixer.c's celeste_audio_init).
  <out>/audio_tables.h   -- sfx_offset[]/sfx_length[] (bytes into sfx.bin)
                            indexed by sound id, SFX_SAMPLE_RATE, and
                            SFX_TABLE_COUNT. Small; compiled into the .rock.

Usage: gen_audio.py <repo_root> <out_dir>
"""

import sys
import wave
from pathlib import Path

SFX_IDS = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 13, 14, 15, 16, 23, 35, 37, 38, 40, 50, 51, 54, 55]


def read_wav_pcm16_mono(path):
    with wave.open(str(path), "rb") as w:
        assert w.getsampwidth() == 2, f"{path}: expected 16-bit PCM"
        assert w.getnchannels() == 1, f"{path}: expected mono"
        rate = w.getframerate()
        raw = w.readframes(w.getnframes())
    return rate, raw


def main():
    if len(sys.argv) != 3:
        raise SystemExit("usage: gen_audio.py <repo_root> <out_dir>")
    repo_root = Path(sys.argv[1]).resolve()
    out_dir = Path(sys.argv[2]).resolve()
    out_dir.mkdir(parents=True, exist_ok=True)
    data_dir = repo_root / "ports/SDL2/Sources/CelesteSDL2/Resources/data"

    sfx_blob = bytearray()
    entries = []
    max_sfx_id = max(SFX_IDS)
    sample_rate = None
    for sound_id in range(max_sfx_id + 1):
        if sound_id not in SFX_IDS:
            entries.append((0, 0))
            continue
        rate, pcm16 = read_wav_pcm16_mono(data_dir / f"snd{sound_id}.wav")
        if sample_rate is None:
            sample_rate = rate
        elif rate != sample_rate:
            raise SystemExit(
                f"snd{sound_id}.wav is {rate}Hz, expected {sample_rate}Hz "
                "(all clips must share one rate -- mixer.c doesn't resample)")
        entries.append((len(sfx_blob), len(pcm16)))
        sfx_blob += pcm16
    (out_dir / "sfx.bin").write_bytes(sfx_blob)

    offsets = ", ".join(str(o) for o, _ in entries)
    lengths = ", ".join(str(l) for _, l in entries)
    (out_dir / "audio_tables.h").write_text(
        "/* Generated by ports/iPod/tools/gen_audio.py - do not edit. */\n"
        "#ifndef CELESTE_AUDIO_TABLES_H\n"
        "#define CELESTE_AUDIO_TABLES_H\n\n"
        f"#define SFX_TABLE_COUNT {len(entries)}\n"
        f"#define SFX_SAMPLE_RATE {sample_rate}\n\n"
        "/* Byte offset/length of each sound id's clip within sfx.bin; "
        "length 0 for an unmapped id. */\n"
        f"static const unsigned int sfx_offset[SFX_TABLE_COUNT] = {{ {offsets} }};\n"
        f"static const unsigned int sfx_length[SFX_TABLE_COUNT] = {{ {lengths} }};\n\n"
        "#endif\n"
    )

    print(f"sfx.bin: {len(entries)} ids, {len(sfx_blob)} bytes ({len(sfx_blob) / 1024:.1f} KB) @ {sample_rate}Hz")


if __name__ == "__main__":
    main()
