/***************************************************************************
 *
 * mixer.c -- SFX playback for the Celeste Rockbox port, phase v1 of the
 * audio plan in ports/iPod/README.md (silent -> SFX -> music). Music is
 * still a no-op; see rb_audio_music below.
 *
 * sfx.bin (~1.5MB of concatenated PCM16 mono clips, generated by
 * tools/gen_audio.py from the same WAVs the SDL2 port uses) is too big for
 * the 512KB plugin buffer, so it isn't linked into celeste.rock -- it's
 * installed to /.rockbox/celeste/sfx.bin and loaded into the ~28MB audio
 * buffer at startup. audio_tables.h (generated alongside it, but tiny) is
 * linked in and gives the offset/length of each sound id's clip.
 *
 * Playback rides Rockbox's channel mixer (mixer_channel_play_data on
 * PCM_MIXER_CHAN_PLAYBACK), the same API apps/plugins/doom/i_sound.c uses
 * to mix its 24 internal channels down to one stream: we do the same thing
 * with a much smaller fixed set of one-shot voices, summed on the fly in
 * the mixer's get_more callback.
 *
 * THREADING NOTE: rb_audio_sfx (called from Swift, on the plugin's main
 * thread) writes a voice slot's data/remaining fields; mixer_get_more
 * (called from whatever context Rockbox's mixer runs get_more callbacks
 * in) reads and mutates those same fields. Neither side does anything but
 * plain word reads/writes/pointer-advances -- no allocation, no Swift
 * involvement -- so the worst case from a torn read is a dropped or
 * glitched sample on the frame a new sfx starts, never a crash. Doom's own
 * mixer has the same property for the same reason.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 ****************************************************************************/

#include "plugin.h"
#include "pcm_sampr.h"
#include "rockbox_shim.h"
#include "audio_tables.h"

#define CELESTE_SFX_PATH ROCKBOX_DIR "/celeste/sfx.bin"

/* One-shot voices; a burst of simultaneous sfx (e.g. jump + dash) just
 * round-robins across these rather than needing a priority scheme -- fine
 * for a handful of short clips. */
#define NUM_VOICES 4
#define MIX_FRAMES 128 /* stereo frames per get_more call, matches doom's SAMPLECOUNT */

struct voice {
    const int16_t *data;
    size_t remaining; /* samples left, not bytes */
};

static struct voice voices[NUM_VOICES];
static int16_t mixbuf[MIX_FRAMES * 2]; /* interleaved stereo */
static const int16_t *sfx_pcm;
static bool mixer_running;

static int32_t clip16(int32_t v)
{
    if (v > 32767)
        return 32767;
    if (v < -32768)
        return -32768;
    return v;
}

static void mix_update(void)
{
    int i, v;

    for (i = 0; i < MIX_FRAMES; i++) {
        int32_t sum = 0;

        for (v = 0; v < NUM_VOICES; v++) {
            if (voices[v].remaining > 0) {
                sum += *voices[v].data++;
                voices[v].remaining--;
            }
        }
        mixbuf[i * 2] = mixbuf[i * 2 + 1] = (int16_t)clip16(sum);
    }
}

static void mixer_get_more(const void **start, size_t *size)
{
    mix_update();
    *start = mixbuf;
    *size = sizeof(mixbuf);
}

static const struct mixer_play_cbs mixer_cbs = { .get_more = mixer_get_more };

/* Loads sfx.bin into the audio buffer and starts a continuous (silence-
 * filled when idle) playback channel. Safe to fail -- the game runs fine
 * silent if this returns nonzero (missing file, or celeste_shim_init
 * already claimed the audio buffer as its heap fallback). */
int celeste_audio_init(void)
{
    int fd;
    size_t need, have;
    void *buf;

    fd = rb->open(CELESTE_SFX_PATH, O_RDONLY);
    if (fd < 0)
        return -1;

    need = (size_t)rb->filesize(fd);
    buf = rb->plugin_get_audio_buffer(&have);
    if (buf == NULL || have < need || rb->read(fd, buf, need) != (ssize_t)need) {
        rb->close(fd);
        return -1;
    }
    rb->close(fd);

    sfx_pcm = (const int16_t *)buf;

    rb->mixer_set_frequency(SFX_SAMPLE_RATE);
    rb->mixer_channel_play_data(PCM_MIXER_CHAN_PLAYBACK, &mixer_cbs, NULL, 0);
    mixer_running = true;
    return 0;
}

void celeste_audio_shutdown(void)
{
    if (!mixer_running)
        return;
    rb->mixer_channel_stop(PCM_MIXER_CHAN_PLAYBACK);
    rb->mixer_set_frequency(HW_SAMPR_DEFAULT);
    mixer_running = false;
}

void rb_audio_sfx(int id)
{
    static int next_voice;
    unsigned int offset, length;
    int v;

    if (sfx_pcm == NULL || id < 0 || id >= SFX_TABLE_COUNT)
        return;
    length = sfx_length[id];
    if (length == 0)
        return; /* unmapped id */
    offset = sfx_offset[id];

    v = next_voice;
    next_voice = (next_voice + 1) % NUM_VOICES;

    voices[v].data = sfx_pcm + offset / sizeof(int16_t);
    voices[v].remaining = length / sizeof(int16_t);
}

void rb_audio_music(int index, int fade_ms)
{
    /* Phase v2, not implemented yet -- see ports/iPod/README.md. */
    (void)index;
    (void)fade_ms;
}
