#!/usr/bin/env python3
"""Build-time audio converter for the Nintendo 3DS port.

Converts ccleste's original sound-effect/music clips (vendored under
ports/SDL2/Sources/CelesteSDL2/Resources/data/, already used by that port) to
signed 16-bit PCM mono at native sample rate -- what NDSP's
NDSP_FORMAT_MONO_PCM16 plays directly, no runtime decoder (see
source/Audio.swift / common/shim.c's ctru_play_pcm16).

sndN.wav files are already 16-bit PCM mono and are read directly; musN.ogg
tracks are decoded via macOS's built-in `afconvert` (this step is therefore
macOS-only, matching ports/Darwin's audio pipeline). Sound ids/music indices
match CelesteAudio's `sfx(_:)`/`music(index:)` exactly (see
Sources/CelesteCore/CelesteEngine.swift's psfx/audio.music call sites).

Emits:
  <out>/sfx.bin           -- every sndN.wav's PCM16 samples, concatenated in
                             id order.
  <out>/music.bin         -- every musN.ogg's PCM16 samples, concatenated in
                             index/10 order.
  <out>/AudioAssets.swift -- sfxClipTable[id] / musicClipTable[index/10],
                             each (offset, length, sampleRate) in bytes.

Usage: gen_audio.py <repo_root> <out_dir>
"""

import subprocess
import struct
import sys
import tempfile
import wave
from pathlib import Path

SFX_IDS = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 13, 14, 15, 16, 23, 35, 37, 38, 40, 50, 51, 54, 55]
MUSIC_INDICES = [0, 10, 20, 30, 40]


def read_wav_pcm16_mono(path):
    with wave.open(str(path), "rb") as w:
        assert w.getsampwidth() == 2, f"{path}: expected 16-bit PCM"
        channels = w.getnchannels()
        rate = w.getframerate()
        raw = w.readframes(w.getnframes())
    if channels == 1:
        return rate, raw
    count = len(raw) // 2
    samples = list(struct.unpack(f"<{count}h", raw))
    frames = count // channels
    mono = [0] * frames
    for i in range(frames):
        frame = samples[i * channels : (i + 1) * channels]
        mono[i] = sum(frame) // channels
    return rate, struct.pack(f"<{len(mono)}h", *mono)


def decode_ogg_to_pcm16_mono(path, tmpdir):
    wav_path = tmpdir / (path.stem + ".wav")
    subprocess.run(
        ["afconvert", "-f", "WAVE", "-d", "LEI16", "-c", "1", str(path), str(wav_path)],
        check=True, capture_output=True)
    return read_wav_pcm16_mono(wav_path)


def emit_table(name, entries):
    lines = ",\n  ".join(
        f"(offset: {offset}, length: {length}, sampleRate: {rate})"
        for offset, length, rate in entries)
    return (
        f"let {name}: [(offset: Int32, length: Int32, sampleRate: Int32)] = [\n"
        f"  {lines},\n"
        "]\n"
    )


def main():
    if len(sys.argv) != 3:
        raise SystemExit("usage: gen_audio.py <repo_root> <out_dir>")
    repo_root = Path(sys.argv[1]).resolve()
    out_dir = Path(sys.argv[2]).resolve()
    out_dir.mkdir(parents=True, exist_ok=True)
    data_dir = repo_root / "ports/SDL2/Sources/CelesteSDL2/Resources/data"

    sfx_blob = bytearray()
    sfx_entries = []
    max_sfx_id = max(SFX_IDS)
    for sound_id in range(max_sfx_id + 1):
        if sound_id not in SFX_IDS:
            sfx_entries.append((0, 0, 0))
            continue
        src = data_dir / f"snd{sound_id}.wav"
        rate, pcm16 = read_wav_pcm16_mono(src)
        sfx_entries.append((len(sfx_blob), len(pcm16), rate))
        sfx_blob += pcm16
    (out_dir / "sfx.bin").write_bytes(sfx_blob)

    music_blob = bytearray()
    music_entries = []
    with tempfile.TemporaryDirectory() as tmp:
        tmpdir = Path(tmp)
        for index in MUSIC_INDICES:
            src = data_dir / f"mus{index}.ogg"
            rate, pcm16 = decode_ogg_to_pcm16_mono(src, tmpdir)
            music_entries.append((len(music_blob), len(pcm16), rate))
            music_blob += pcm16
    (out_dir / "music.bin").write_bytes(music_blob)

    (out_dir / "AudioAssets.swift").write_text(
        "// Generated by ports/3DS/tools/gen_audio.py - do not edit.\n\n"
        "/// Byte offset/length/sample-rate of each sound-effect id's signed 16-bit\n"
        "/// PCM mono clip within sfx.bin; `length == 0` for an unmapped id.\n"
        + emit_table("sfxClipTable", sfx_entries)
        + "\n"
        "/// Byte offset/length/sample-rate of each music track (index/10, matching\n"
        "/// CelesteAudio.music(index:)) within music.bin.\n"
        + emit_table("musicClipTable", music_entries)
    )

    print(f"sfx.bin: {len(sfx_entries)} clips, {len(sfx_blob)} bytes ({len(sfx_blob) / 1024:.1f} KB)")
    print(f"music.bin: {len(music_entries)} clips, {len(music_blob)} bytes ({len(music_blob) / 1024:.1f} KB)")


if __name__ == "__main__":
    main()
